import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import './globals.css'
import AppHeader from '@/components/app.header'
import AppFooter from '@/components/app.footer'

const jostFont = Jost({
  weight: ['400', '700'],
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${jostFont.className} bg-[#D6D7EF]`}>
        <AppHeader />

        {children}

        <AppFooter />
      </body>
    </html>
  )
}
